config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :sale_prices, only: [:index, :create, :destroy]
    end
  end

  get '/sale',        to: 'home#sale', as: :sale
  get '/sale/t/*id/', to: 'home#sale', as: :sale_taxon
end

app/models/spree/sale_price.rb
module Spree
  class SalePrice < ActiveRecord::Base
    attr_accessor :currency, :variant

    # TODO: validations
    belongs_to :default_price, class_name: "Spree::Price", foreign_key: "price_id"
    belongs_to :price, class_name: "Spree::Price"
    has_one :calculator, class_name: "Spree::Calculator", as: :calculable, dependent: :destroy

    accepts_nested_attributes_for :calculator

    validates :calculator, presence: true
    validates :value, numericality: { greater_than: 0 }

    validates_presence_of :start_at
    validates :end_at, date: { after: :start_at, allow_blank: true }

    delegate :currency, to: :default_price

    scope :active, -> { where(enabled: true).where("(start_at <= ? OR start_at IS NULL) AND (end_at >= ? OR end_at IS NULL)", Time.now, Time.now) }

    def initialize attrs={}
      attrs[:calculator] = attrs[:calculator].constantize.new if attrs && attrs[:calculator].present?

      super attrs
    end

    def calculator_type
      calculator.class.to_s if calculator
    end

    def new_amount
      calculator.compute self
    end

    def enable
      update_attribute(:enabled, true)
    end

    def disable
      update_attribute(:enabled, false)
    end

    def start(end_time=nil)
      end_time = nil if end_time.present? && end_time <= Time.now # if end_time is not in the future then make it nil (no end)
      attr = {end_at: end_time, enabled: true}
      attr[:start_at] = Time.now if start_at.present? && start_at > Time.now # only set start_at if it's not set in the past
      update_attributes(attr)
    end

    def stop
      update_attributes(end_at: Time.now, enabled: false)
    end

    # Convenience method for displaying the price of a given sale_price in the table
    def display_price
      Spree::Money.new(new_amount, currency: currency)
    end

    # Custom method: For adding sale price validation #
    def validate_value value, params
      unless params['variant'] == 'all_variants'
        variant = Spree::Variant.where(id: params['variant']).first
        return false unless variant
      end

      valid_sale = true
      if params['calculator'] == 'Spree::Calculator::AmountSalePriceCalculator'
        if variant && value.to_f > variant.original_price.to_f
          errors.add(:value, 'value should not be greater than the original price')
          valid_sale = false
        end
      else
        unless value.to_f.between?(0.0, 1.0)
          errors.add(:value, "percent should between 0.0 and 1.0 (#{calculator.class.title})")
          valid_sale = false
        end
      end
      return valid_sale
    end
  end
end

app/controllers/spree/admin/sale_prices_controller.rb
module Spree
  module Admin
    class SalePricesController < BaseController
      before_action :load_product
      before_action :load_sale_prices

      respond_to :js, :html

      # Show all sale prices for a product
      def index
        @sale_price = Spree::SalePrice.new
      end

      # Create a new sale price
      def create
        @sale_price = Spree::SalePrice.new sale_price_params
        # rails 5 the belongs_to association is required by default
        @sale_price.price = @product.master.default_price

        if @sale_price.valid? && @sale_price.validate_value(sale_price_params[:value], sale_price_params)
          @product.put_on_sale sale_price_params[:value], sale_price_params
          redirect_to admin_product_sale_prices_path(@product)
        else
          render :index
        end
      end

      # Destroy a sale price
      def destroy
        sale_price = Spree::SalePrice.find(params[:id])
        sale_price.destroy
        @product.touch

        respond_with(sale_price)
      end

      private

      # Load the product as a before filter. Redirect to the referer if no product is found
      def load_product
        @product = Spree::Product.find_by(slug: params[:product_id])
        redirect_to request.referer unless @product.present?
      end

      # Load product sale_prices as a before filter.
      def load_sale_prices
        @sale_prices = @product.sale_prices

        @variants = @product.variants_including_master.map do |variant|
          [variant.id, variant.sku_and_options_text]
        end

        @variants.insert(0, [:all_variants, Spree.t(:all_variants)])
      end

      # Sale price params
      def sale_price_params
        params.require(:sale_price).permit(
          :value,
          :start_at,
          :end_at,
          :currency,
          :variant,
          :calculator
        )
      end
    end
  end
end

app/views/spree/admin/sale_prices/_form.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @sale_price } %>

<div id="add_sales_price_form" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= Spree.t('add_product_sale_prices') %></h1>
  </div>
    <div class="panel-body">
    <%= form_for [:admin, @product, @sale_price] do |f| %>
      <div class="row">
        <div class="col-md-4 form-group">
          <%= f.label :calculator %>
          <%= f.select :calculator, sale_calculators, {}, {:class => 'select2'} %>
        </div>

        <div class="col-md-4 form-group">
          <%= f.label :currency %>
          <%= select_tag "sale_price[currency]", spree_sale_currencies, class: 'select2' %>
        </div>

        <div class="col-md-4 form-group">
          <%= f.label :variant %>
          <%= select_tag "sale_price[variant]", options_from_collection_for_select(@variants, :first, :last, @product.master.id), class: 'select2' %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 form-group">
          <%= f.label :value, raw(Spree.t(:sale_price) + content_tag(:span, ' *', class: 'required')) %>
          <%= f.text_field :value, class: "form-control", required: true %>
        </div>

        <div class="col-md-4 form-group">
          <%= f.label :start_at, raw(Spree::SalePrice.human_attribute_name(:start_at) + content_tag(:span, ' *', class: 'required')) %>
          <%= f.text_field :start_at, class: "datepicker form-control", required: true %>
        </div>
        <div class="col-md-4 form-group">
          <%= f.label :end_at %>
          <%= f.text_field :end_at, class: "datepicker form-control" %>
        </div>
      </div>
      <div class="form-actions text-center" data-hook="buttons">
        <%= f.submit Spree.t("add_product_sale_prices"), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/admin/sale_prices/_product_tab.html.erb
<%= content_tag :li, :class => ('active' if current == Spree.t(:product_sale_prices)) do %>
  <%= link_to_with_icon 'usd', Spree.t(:product_sale_prices), admin_product_sale_prices_path(@product), class: "nav-link" %>
<% end %>

app/views/spree/admin/sale_prices/_sale_price.html.erb
<tr class="spree-product-sale-price" id="<%= spree_dom_id(variant) %>">
  <td> <%= active_for_sale_price(variant, sale_price) ? Spree.t(:yes) : '' %> </td>
  <td> <%= display_original_price(variant) %> </td>
  <td> <%= sale_price.display_price.to_html %></td>
  <td> <%= sale_price.start_at.to_date %> </td>
  <td> <%= sale_price.end_at.try :to_date %> </td>
  <td> <%= sale_price.enabled %> </td>
  <td class="actions"> <%= link_to_delete sale_price, {:url => admin_product_sale_price_url(product, sale_price.id), :no_text => true} %> </td>
</tr>

app/views/spree/admin/sale_prices/_table.html.erb
<table class="table table-bordered" data-hook="sale_price_table" id="product_sale_prices">
  <thead>
    <tr data-hook="products_header">
      <th colspan="2"> <%= Spree.t('variant') %> </th>
      <th> <%= Spree.t('sales_info') %> </th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "variant", collection: product.variants_including_master, locals: {product: product} %>
  </tbody>
</table>

app/views/spree/admin/sale_prices/_variant.html.erb
<tr id="<%= spree_dom_id(variant) %>">
  <td class="image text-center">

    <% if variant.images.present? %>
      <%= mini_image variant %>
    <% end %>
  </td>
  <td><%= variant_sku_text(variant) %></td>
  <td>
    <%- if variant.sale_prices.any? %>
      <table class="table table-bordered no-marginb">
        <thead>
          <th> <%= Spree.t('sale_price_active') %></th>
          <th> <%= Spree.t('price') %> </th>
          <th> <%= Spree.t('sale_price') %> </th>
          <th> <%= Spree.t('sale_price_start_at') %> </th>
          <th> <%= Spree.t('sale_price_end_at') %> </th>
          <th> <%= Spree.t('sale_price_enabled') %> </th>
          <th class="actions text-center"></th>
        </thead>
        <tbody>
          <%= render partial: "sale_price", collection: variant.sale_prices, locals: { product: product, variant: variant } %>
        </tbody>
      </table>
    <%- else %>
      <div class="no-objects-found alert alert-info">
        <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::SalePrice)) %>
      </div>
    <% end %>
  </td>
</tr>

app/views/spree/admin/sale_prices/destroy.js.erb
$('table#product_sale_prices').replaceWith('<%= j render partial: "table", locals: { product: @product } %>');

app/views/spree/admin/sale_prices/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Product Sale Prices"} %>
<%= csrf_meta_tag %>

<%= render 'spree/admin/sale_prices/form' %>

<div id="product-sale-prices-table">
  <%= render partial: "table", locals: { product: @product } %>
</div>